TRAIN_PATH = 'D:\\Code\\Kaggle\\Movie Review Sentiment Analysis\\dataset\\train.tsv'
SHUFFLE = True
NUM_WORKERS = 1
EPOCHS = 5
BATCH_SIZE = 4
WORD_TO_INDEX_PATH = 'D:\\Code\\Kaggle\\Movie Review Sentiment Analysis\\dataset\\word_to_index.json'
GLOVE_PATH = 'D:\\datasets\\GLOVE\\glove.840B.300d.txt'
EMBEDDING_SIZE = 128
HIDDEN_SIZE = 256
ALPHA = 1e-3
MODEL_PATH = r'D:\Code\Kaggle\Movie Review Sentiment Analysis\models\train.pth'
SAVE = True
MODEL_TYPE = "LSTM" 
VOCAB_SIZE = 13554
NUM_LAYERS = 1
DROPOUT = 0
BIDIRECTIONAL = True